version: '3'
services:
  # web:
  #   build: .
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
  ### Redis ################################################
  redis:
    image: redis:alpine
    command: redis-server --requirepass redis@123
    ports:
      - 6379:6379
    volumes:
      - ./docker/data/redis:/var/lib/redis
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
